import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Image from 'next/image'

export default function Home() {
  return (
    <div className="bg-[#050346] h-screen">
      <Head>
        <title>Retr0x</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="items-center justify-center text-center p-40">
        <Image src='/logo.jpeg' width="600" height="400" className="mb-20"></Image>
        <br></br>
        <br></br>
        <br></br>
        <Link href="/rounds">
          <a class="bg-white text-black p-4 rounded-2xl mt-20 z-50 text-lg">Launch app</a>
        </Link>

      </main>
    </div>
  )
}
