import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Meet Retro - the future of public goods funding
        </h1>

        <Link href="/rounds">
          <a className="bg-gradient-to-r from-purple-600 to-blue-800 text-white p-4 rounded-2xl mt-4 font-large">Launch app</a>
        </Link>

      </main>

      <footer className={styles.footer}>
        <p>
          Made with {String.fromCodePoint('0x2764')} by the Oxford Team
        </p>
      </footer>
    </div>
  )
}
