import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Rounds() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-center text-6xl">
        <h1>
          Rounds
        </h1>

      </main>
    </div>
  )
}
