import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import {rounds} from './data/rounds'
import { useRouter } from 'next/router'

export default function Rounds() {
  const router = useRouter()
  const roundID = router.query.id;
  const round = rounds.find(o => o.id == roundID);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-center text-6xl">
        <h1>
          {round.name}
        </h1>

      </main>
    </div>
  )
}
